# Generated by Django 5.2.17 on 2026-08-12 14:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_organizer_event_tmdb_id_session_sold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticketmaster_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='session',
            name='seat_cols',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='seat_rows',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='seating_mode',
            field=models.CharField(choices=[('quantity', 'Pista / quantidade'), ('seats', 'Mapa de assentos')], default='quantity', max_length=20),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row', models.CharField(max_length=4)),
                ('number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('available', 'Disponível'), ('held', 'Reservado'), ('sold', 'Vendido')], default='available', max_length=20)),
                ('held_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_seats', to='events.order')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='events.session')),
            ],
            options={
                'ordering': ['row', 'number'],
                'unique_together': {('session', 'row', 'number')},
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='events.seat'),
        ),
    ]
