services:
  - type: pserv
    name: ingresso-mysql
    runtime: docker
    repo: https://github.com/render-examples/mysql.git
    plan: starter
    envVars:
      - key: MYSQL_DATABASE
        value: ingresso
      - key: MYSQL_USER
        value: ingresso
      - key: MYSQL_PASSWORD
        generateValue: true
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 10

  - type: web
    name: ingresso-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    healthCheckPath: /api/events/
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: CORS_ALLOW_ALL
        value: "true"
      - key: MYSQL_PORT
        value: "3306"
      - key: MYSQL_DATABASE
        value: ingresso
      - key: MYSQL_USER
        value: ingresso
      - key: MYSQL_HOST
        fromService:
          name: ingresso-mysql
          type: pserv
          property: host
      - key: MYSQL_PASSWORD
        fromService:
          name: ingresso-mysql
          type: pserv
          envVarKey: MYSQL_PASSWORD
      - key: TMDB_API_KEY
        sync: false
      - key: TICKETMASTER_API_KEY
        sync: false
